- README.md
- app-full-microprofile/threshold.properties
- app-generated-skeleton/README.md
- app-generated-skeleton/application.properties
- app-generated-skeleton/threshold.properties
- pom.xml
- testsuite/pom.xml
- testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/StartStopTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/Apps.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/LogBuilder.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/Logs.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/MvnCmds.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/URLContent.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/Whitelist.java
See [Doc](https://github.com/Karm/quarkus-startstop/blob/generating-apps/README.md#artifactgeneratortest)
> Maven Generator test harness

- README.md
- app-generated-skeleton/application.properties
- app-generated-skeleton/settings.xml
- pom.xml
- testsuite/pom.xml
- testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorBOMTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/StartStopTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/Apps.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/FakeOIDCServer.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/Logs.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/MvnCmds.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/TestFlags.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistProductBomJars.java
All, including productized Quarkus builds nad native images:
```
mvn clean verify -Ptestsuite 
-Dquarkus.version=1.3.0.Final-redhat-00019
-Dquarkus.platform.version=1.3.0.Final-redhat-00010
-Dtests.maven.repo.local=/home/karm/QUARKUS/quarkus-1.3.0.ER11/maven-repository
-Dmaven.repo.local=/home/karm/QUARKUS/quarkus-1.3.0.ER11/maven-repository
```
Community version, including native images:
```
mvn clean verify -Ptestsuite-community -Dquarkus.version=1.3.0.Final
```
> Implements BOM tests for generator

- README.md
- testsuite/pom.xml
- testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorBOMTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/Logs.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/MvnCmds.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WebpageTester.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
- testsuite/src/it/resources/JSONtoEnum.java
- testsuite/src/it/resources/README.md
@rsvoboda Kinda the first thing. It blindly trusts "supported" tags. It should also compare that with hardcoded String[] of extensions to verify the Code Quarkus is making sense...
> Code Quarkus tests

- README.md
- testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorBOMTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/StartStopTest.java
- Details about tests
- Updated README.md
> Updated README.md and details about tests

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/FakeOIDCServer.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/LogBuilder.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/Logs.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
- Make header strings in LogBuilder static
- Ensure UTF-8 usage instead of platform default charset
> Fixes for issues reported by Coverity

- .gitignore
> .gitignore update for VS Code

- README.md
- pom.xml
- testsuite/src/it/java/io/quarkus/ts/startstop/SpecialCharsTest.java
Added test for special characters on path to application.
> first draft

- .mvn/wrapper/MavenWrapperDownloader.java
- .mvn/wrapper/maven-wrapper.properties
- mvnw
- mvnw.cmd
Adding Maven wrapper to project to facilitate Maven builds on environments without Maven.
> Adding mvnw

- testsuite/src/it/java/io/quarkus/ts/startstop/StartStopTest.java
StartStopTest - measure time and rss size from multiple runs
Running 10 iterations, removing Min and Max value to eliminate the extremes, computing average from the remaining numbers
Should help to get more stable results and to enable runs on virtualized environment like OpenStack
> StartStopTest - measure time and rss size from multiple runs

- README.md
> Troubleshooting section in README

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java
Compilation fix for CodeQuarkusExtensions
> Compilation fix for CodeQuarkusExtensions

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
> Whitelist WebJars warning

- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WebpageTester.java
Test coverage for Jira Issues IDs: Quarkus-142, Quarkus-141
Test main goal is to validate that required elements are present at the certain web page.
> Add test to validate presence of web elements on the page

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/Logs.java
1.7 branch variant of https://github.com/quarkus-qe/quarkus-startstop/pull/45
> Fix SLF4J check

- README.md
- testsuite/src/it/java/io/quarkus/ts/startstop/NativeDebugTest.java
**Pending state**. Awaiting the next version of Quarkus to be released.
TD for Quarkus native debug mode. The test is checked against  1.9.1.Final version of Quarkus
> Add test native debug mode for Quarkus

- .github/workflows/ci.yaml
Include directories and files under archived-logs
ATM only the root `archived-logs` directory is included
> Include directories and files under archived-logs

- app-full-microprofile/pom.xml
- pom.xml
- testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
Move Quarkus from 1.11.0.Final to 1.11.1.Final
> Move Quarkus from 1.11.0.Final to 1.11.1.Final

- testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
New blessed extensions for RHBQ 1.11
We label extensions just as supported and unsupported, no notion of TP.
SRye metrics marked as unsupported due to collision with micrometer extension.
> New blessed extensions for RHBQ 1.11

- .github/workflows/ci.yaml
- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/MvnCmds.java
Verify only the supported extensions with code starters.
> Verify Extensions with Code Starters

- testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorBOMTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/SpecialCharsTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/StartStopTest.java
Changes requested as part of this comment: https://github.com/quarkus-qe/quarkus-startstop/pull/57#discussion_r572777444
> Do runCommand after appendln statements

- testsuite/src/it/resources/JSONtoEnum.java
JSONtoEnum util - relax https requirement
> JSONtoEnum util - relax https requirement

- .github/workflows/ci.yaml
- pom.xml
- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/SpecialCharsTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/MvnCmds.java
> Bump to Quarkus 1.12.0.Final

- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
- CodeQuarkusExtensions - update of supported extensions
- CodeQuarkusTest - Native tag for supportedExtensionWithCodeStarterWorksInNative tests
- CodeQuarkusSiteTest - use defined URL instead of hardcoded one
> CodeQuarkusExtensions ++ CodeQuarkusTest ++ CodeQuarkusSiteTest update

- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/StartStopTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/Logs.java
When running the Quarkus app in DEV mode, it will listen localhost. Otherwise, it will listen in 0.0.0.0.
> Verify the listening port

- .github/workflows/ci.yaml
> Fix archived artifacts names

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java
quarkus-smallrye-jwt works out of the box
master PR: https://github.com/quarkus-qe/quarkus-startstop/pull/68
https://issues.redhat.com/browse/QUARKUS-140
quarkusio/quarkus#8506
> quarkus-smallrye-jwt works out of the box

- pom.xml
- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java
Enhance testcase according to https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-821.md
Main PR https://github.com/quarkus-qe/quarkus-startstop/pull/73
> [1.11] Enhance test for code.quarkus.redhat.com site

- testsuite/pom.xml
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
Backport of https://github.com/quarkus-qe/quarkus-startstop/pull/80
> [1.11] Maven 3.8.1 rise a warning msg that makes some test fail

- testsuite/src/it/resources/JSONtoEnum.java
Fix the index for shortId and name
> Fix the index for shortId and name

- .github/workflows/ci.yaml
Bump graalvm-version to 21.1.0.java11
> Bump graalvm-version to 21.1.0.java11

- pom.xml
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java
> Move to Quarkus 2.1.0.Final

- app-generated-skeleton/application.properties
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
Updates to reflect code.quarkus update to version 2.1.0.Final
> Updates to reflect code.quarkus update to version 2.1.0.Final

- app-generated-skeleton/threshold.properties
- pom.xml
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
> Upgrade Quarkus to 2.1.1.Final

- testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/Logs.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/MvnCmds.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/TestFlags.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
Backport of https://github.com/quarkus-qe/quarkus-startstop/pull/113
> [2.2] Fix quarkus maven plugin group ID ++ Disable Quarkus Registry Client to boost generator Maven commands

- pom.xml
- testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorBOMTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/TestFlags.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/URLContent.java
RESTEasy reactive based extensions sets
backport of https://github.com/quarkus-qe/quarkus-startstop/pull/117
> RESTEasy reactive based extensions sets

- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java
Backport of https://github.com/quarkus-qe/quarkus-startstop/pull/119
> Change xpath to get current version ID from Code Starter

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java
Re-enable extensions from platform participants
> Re-enable extensions from platform participants

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
Backport of https://github.com/quarkus-qe/quarkus-startstop/pull/123
> [2.2] Ignore some trace messages in Windows

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistProductBomJars.java
Related to https://issues.redhat.com/browse/QUARKUS-1201?focusedCommentId=19095005&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-19095005
> Ignore some com.microsoft and com.nimbusds unproductised artifacts

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistProductBomJars.java
Related to https://issues.redhat.com/browse/QUARKUS-1201?focusedCommentId=19095005&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-19095005
Backport of https://github.com/quarkus-qe/quarkus-startstop/pull/127
> [2.2] Ignore some com.microsoft and com.nimbusds unproductised artifacts

- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java
Workaround for quarkus-grpc regression - https://github.com/quarkusio/quarkus/issues/21132
> Workaround for quarkus-grpc regression

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
Changes for Quarkus 2.5.1.Final - code.quarkus
> Changes for Quarkus 2.5.1.Final - code.quarkus

- .github/workflows/ci.yaml
- pom.xml
Full move to Qaurkus 2.5.1.Final
> Full move to Qaurkus 2.5.1.Final

- pom.xml
- testsuite/pom.xml
Non-Quarkus dependencies update
> Non-Quarkus dependencies update

- app-jax-rs-minimal/threshold.properties
Revert "Increase time.to.first.ok.request.threshold.ms for JAX-RS minimal app"
This reverts commit e229a3198566f3584e94ffc5474b1b55fd231c94.
Quarkus 2.5 has several improvements as indicated in https://github.com/quarkusio/quarkus/issues/21149.
> Revert "Increase time.to.first.ok.request.threshold.ms for JAX-RS minimal app"

- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java
Fixes for 2.5.2.Final based code.quarkus
- Regression in SmallRye GraphQL + Oracle driver combination
- Ensure page with extension entries is loaded
> Fixes for 2.5.2.Final based code.quarkus

- .github/workflows/ci.yaml
- pom.xml
> [2.2] Update to Quarkus 2.2.4.Final

- .github/workflows/ci.yaml
Enable manual trigerring from GitHub UI
> Enable manual trigerring from GitHub UI

- pom.xml
> Quarkus 2.5.4.Final

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/MvnCmds.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
Produce dependency tree as part of the execution
> Produce dependency tree as part of the execution

- testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java
Drop logging-json to have human readable logs
> Drop logging-json to have human readable logs

- testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java
Drop logging-json for reactive set to have human readable logs
> Drop logging-json for reactive set to have human readable logs

- testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java
Issue https://github.com/quarkusio/quarkus/issues/18843 has been fixed
> Add websockets extension in ArtifactGenerator test

- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java
Ensure SmallRye Health codestart
SmallRye Health already covered in `ArtifactGeneratorTest` and `ArtifactGeneratorBOMTest`
> Ensure SmallRye Health codestart

- testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java
> [2.2] Add websockets extension in ArtifactGenerator test

- testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/SpecialCharsTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java
ArtifactGenerator tests GH issues cleanup
> ArtifactGenerator tests GH issues cleanup

- pom.xml
- testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
Move to Quarkus 2.7, remove workarounds
> Move to Quarkus 2.7, remove workarounds

- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java
Backport of https://github.com/quarkus-qe/quarkus-startstop/pull/180
> [2.2] Code.quarkus Site test - Pick the most probable BOM version

- app-full-microprofile/pom.xml
- app-jax-rs-minimal/pom.xml
- pom.xml
- testsuite/src/it/java/io/quarkus/ts/startstop/NativeDebugTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/SpecialCharsTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/StartStopTest.java
> [2.2] Usage of productised plugin and bom to solve plugin not found problem in Jenkins

- pom.xml
> Move to Quarkus 2.7.2.Final

- pom.xml
> Move to Quarkus 2.7.3.Final

- pom.xml
> Bump to Quarkus 2.7.5.Final

- testsuite/src/it/java/io/quarkus/ts/startstop/QuarkusMavenPluginTest.java
QuarkusMavenPluginTest for help/info/update
Relates to https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-1396.md
Focus is on exploratory testing, more automated tests to be developed when CLI is enhanced to support info and update goals
> QuarkusMavenPluginTest for help/info/update

- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java
Update `class` attribute of supported flag element according to the
latest published version of the site.
> Update code.quarkus site test - supported flag

- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
code.quarkus
- validate presence of Java version select
- Java 17 project gets generated
> Java 17 and code.quarkus

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
- testsuite/src/it/resources/README.md
> Notes for API of code.quarkus

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistProductBomJars.java
Ignore community quarkus-resteasy-reactive-links in RHBQ 2.7
details in https://issues.redhat.com/browse/QUARKUS-2033
> Ignore community quarkus-resteasy-reactive-links in RHBQ 2.7

- pom.xml
[Quarkus 2.7.6.Final](https://github.com/quarkusio/quarkus/releases/tag/2.7.6.Final) has been released and branch 2.7 should use it.
Please select the relevant options.
> Update 2.7 branch to use Quarkus 2.7.6

- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java
Use platform BOM
code.quarkus displays platform version now, see https://github.com/quarkusio/code.quarkus.io/pull/910
> Use platform BOM

- pom.xml
- testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java
Bump Quarkus to version 2.10.0.Final
> Bump Quarkus to version 2.10.0.Final

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistProductBomJars.java
> [2.7] Backport "Remove quarkus-resteasy-reactive-links from whitelist & test it"

- pom.xml
Bump Quarkus to version 2.11.1.Final
> Bump Quarkus to version 2.11.1.Final

- .github/workflows/ci.yaml
- testsuite/src/it/java/io/quarkus/ts/startstop/NativeDebugTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
Run just native tests in CI Native builds
(plus make sure NativeDebugTest runs just on Linux)
> Run just native tests in CI Native builds

- .github/workflows/ci.yaml
> Shorter GH Action run names

- pom.xml
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
> Move to Quarkus 2.12.0.Final

- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
Switch to RESTEasy Reactive for code.quarkus tests
> Switch to RESTEasy Reactive for code.quarkus tests

- pom.xml
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
> Bump Quarkus to 2.13.0.CR1

- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java
Test to ensure default Java version for code.quarkus
> Test to ensure default Java version for code.quarkus

- README.md
- testsuite/src/it/java/io/quarkus/ts/startstop/StartStopTest.java
Adjustment of the number of the start-stop cycles
> Adjustment of the number of the start-stop cycles

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
Fix download method with java version.
(align with download method without java version)
> Fix download method with java version

- testsuite/src/it/java/io/quarkus/ts/startstop/StartStopTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/MvnCmds.java
Size of native binary in StartStopTest
> Size of native binary in StartStopTest

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java
New extensions in Quarkus 2.13 platform
> New extensions in Quarkus 2.13 platform

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
> WhitelistLogLines cleanup

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java
Extensions definitions update
Enabled extensions with fixes
Kubernetes Config Promote - QUARKUS-2331 
Mailer Promote - QUARKUS-2387
OpenID Connect Client Filter Reactive Promote - QUARKUS-2389
Quarkus Extension for Spring Data REST Promote - QUARKUS-2388
REST resources for Hibernate ORM with Panache	Promote - QUARKUS-2390
> Extensions definitions update

- pom.xml
> Bump Quarkus to 2.13.3.Final

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
Whitelist for https://github.com/quarkusio/quarkus/issues/28799
> Whitelist for #28810

- .github/workflows/ci.yaml
- testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorBOMTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java
Coverage for quarkus-qpid-jms, make sure released RH artifacts are not used
> Coverage for quarkus-qpid-jms, make sure released RH artifacts are not used

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
- Whitelist fail to index org.osgi.annotation.bundle.Requirements
- Whitelist Kafka complaining about common unknown properties
> Whitelist code.quarkus issues for Quarkus 2.14

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistProductBomJars.java
see https://issues.redhat.com/browse/QUARKUS-2691 for details
> Allow io.github.crac:org-crac to be not productized

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistProductBomJars.java
see https://issues.redhat.com/browse/QUARKUS-2691 for details and https://github.com/quarkus-qe/quarkus-startstop/pull/236 for original PR
> [2.13] Allow io.github.crac:org-crac to be not productized

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/Logs.java
Provide hints for expected productized artifacts
Relates to https://issues.redhat.com/browse/QUARKUS-2072
> Provide hints for expected productized artifacts

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/Logs.java
Provide hints for expected productized artifacts
Relates to https://issues.redhat.com/browse/QUARKUS-2072
> [2.13] Provide hints for expected productized artifacts

- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java
Run validateQuarkusVersionMatch test against 2.13 stream
> Run validateQuarkusVersionMatch test against 2.13 stream

- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
Run validateQuarkusVersionMatch test against 2.7 stream
> Run validateQuarkusVersionMatch test against 2.7 stream

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
Whitelist entry for gRPC in Quarkus 2.15
> Whitelist entry for gRPC in Quarkus 2.15

- README.md
Info about branches
Pointer to https://github.com/quarkus-qe/quarkus-startstop/wiki/New-branch-adjustments
> Info about branches

- .github/workflows/ci.yaml
- pom.xml
- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
Bump Quarkus to 2.13.6.Final
Use code.quarkus.redhat.com
> [2.13] Bump Quarkus to 2.13.6.Final + use code.quarkus.redhat.com

- .github/workflows/ci.yaml
Update GH actions to use latest versions
This removes warnings from GH Actions runs
> Update GH actions to use latest versions

- pom.xml
Bump Quarkus from 2.7.6.Final to 2.7.7.Final
> Bump Quarkus from 2.7.6.Final to 2.7.7.Final

- pom.xml
Upgrade Quarkus to 2.13.7.Final
> [2.13] Bump Quarkus to 2.13.7.Final

- .github/workflows/ci.yaml
- pom.xml
Update dependencies to the latest version
> Update dependencies to the latest version

- .github/workflows/ci.yaml
- pom.xml
Backport from https://github.com/quarkus-qe/quarkus-startstop/pull/259 in hopes, that this will help the CI of https://github.com/quarkus-qe/quarkus-startstop/pull/258
> [2.13] Setup custom Maven for Windows runs

- app-full-microprofile/threshold.properties
- app-jax-rs-minimal/threshold.properties
Thresholds update for GH Actions runners
> Thresholds update for GH Actions runners

- .github/workflows/ci.yaml
Adjust trigger time for daily runs
```
20:00
- BeefyTS
- JDK specifics
- Extensions combinations
22:00
- StartStopTS
23:00
- FW
0:30
- main TS
```
> Adjust trigger time for daily runs

- .github/workflows/ci.yaml
- pom.xml
- testsuite/src/it/java/io/quarkus/ts/startstop/QuarkusMavenPluginTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/MvnCmds.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
> Bump to Quarkus 3.0.1.Final

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
arquillian-bom has wrong sha1 and md5sum
Discussed with jfang who uploaded it, there is nothing he can do about it atm
Fixes daily fails for code.quarkus
> arquillian-bom has wrong sha1 and md5sum

- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java
https://github.com/quarkus-qe/quarkus-startstop/pull/279 follow-up
> Add MongoDB to CodeQuarkusTest native runs to verify no warnings logged

- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java
* Favicon image source location has moved. The test has been updated accordingly.
> [2.13] Updating favicon location in code site test

- pom.xml
> Move to Quarkus 3.2.1.Final

- pom.xml
> Move to Quarkus 3.2.2.Final

- pom.xml
> Bump Quarkus to 3.2.3.Final

- pom.xml
> Bump quarkus version to 3.2.4.Final

- pom.xml
[3.2] Bump Quarkus to 3.2.5.Final
> [3.2] Bump Quarkus to 3.2.5.Final

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
Whitelist xml-apis relocation warning
> [2.13] Whitelist xml-apis relocation warning

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
Whitelist xml-apis relocation warning
> Whitelist xml-apis relocation warning

- .github/workflows/ci.yaml
> Use the latest Mandrel in GitHub actions

- .github/workflows/ci.yaml
> [3.2] Use the Mandrel 23.0.1.2-Final in GitHub CI

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
Handle Quarkus main in getQuarkusGroupId() method
> Handle Quarkus main in getQuarkusGroupId() method

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistProductBomJars.java
> Allow jna and jna-platform artifacts to be not productized backport 3.2.

- testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java
Add quarkus-elasticsearch-rest-client to generator tests, TP in 3.2
> Add quarkus-elasticsearch-rest-client to generator tests, TP in 3.2

- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
Run code.quarkus deployments tests against 3.2 stream
> [3.2] Run code.quarkus deployments tests against 3.2 stream

- pom.xml
> [3.2] Bump Quarkus to 3.2.8.Final

- pom.xml
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
> [2.13] Bump Quarkus to 2.13.9.Final

- pom.xml
Bumps Quarkus from 3.2.8.Final to 3.2.9.Final
> [3.2] Bump Quarkus from 3.2.8.Final to 3.2.9.Final

- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java
Quarkus stream element XPath update
> Quarkus stream element XPath update

- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java
Quarkus stream element XPath update
> [2.13] Quarkus stream element XPath update

- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java
Quarkus stream element XPath update
> [3.2] Quarkus stream element XPath update

- pom.xml
> Bump Quarkus to 3.6.4

- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java
Updated to reflect the changes. Will create backport for 3.2 and 2.13
At the moment expecting 2 test fail
> Fix elements string as they were changed for code quarkus

- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java
> [2.13] Fix elements string as they were changed for code quarkus

- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java
> [3.2] Fix elements string as they were changed for code quarkus

- pom.xml
Bumps Quarkus to 3.2.10.Final.
> [3.2] Bump Quarkus to 3.2.10.Final

- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java
ports https://github.com/quarkus-qe/quarkus-startstop/pull/338
> Use Quarkus platform version from system variable

- testsuite/src/it/java/io/quarkus/ts/startstop/SpecialCharsTest.java
See https://github.com/quarkusio/quarkus/issues/39368 for explanation why the old way stopped to work
> [3.8] Change name of a copied artifact

- pom.xml
Bump Quarkus to 3.8.3
This should help with daily runs / relocation warnings
> Bump Quarkus to 3.8.3

- pom.xml
> [3.8] Bump Quarkus to 3.8.3

- pom.xml
> Bump quarkus to 3.2.11.Final

- testsuite/src/it/java/io/quarkus/ts/startstop/QuarkusMavenPluginTest.java
Fixes https://github.com/quarkus-qe/quarkus-startstop/issues/358
> Run plugin tests in separate directories

- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java
backport of https://github.com/quarkus-qe/quarkus-startstop/pull/362
> [3.8] Change the search for platform version

- pom.xml
Updating Quarkus and Quarkus config version to 3.8.4
> [3.8] Bump Quarkus and Quarkus config version to 3.8.4

- pom.xml
Updating Quarkus and Quarkus config version to 3.9.4
> Bump Quarkus and Quarkus config version to 3.9.4

- README.md
AsyncProfiler (https://github.com/quarkus-qe/quarkus-startstop/pull/371) text update
> AsyncProfiler text update

- pom.xml
Bumping Quarkus and Quarkus config version to 3.8.5
> [3.8] Bump Quarkus to 3.8.5

- pom.xml
Bumping Quarkus and Quarkus config version to 3.13.2
> Bump quarkus version to 3.13.2

- testsuite/src/it/java/io/quarkus/ts/startstop/StartStopTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/Logs.java
Add more clarity for RSS and timeToFirstOKRequest
> Add more clarity for RSS and timeToFirstOKRequest

- .github/workflows/ci.yaml
- pom.xml
- Bump Quarkus from 3.13 to 3.14 
- Bump versions of used actions
> Bump Quarkus from 3.13 to 3.14 , bump versions of used actions

- testsuite/src/it/java/io/quarkus/ts/startstop/SpecialCharsTest.java
Update reasoning for disabled tests in SpecialCharsTest
> Update reasoning for disabled tests in SpecialCharsTest

- pom.xml
> Bump Quarkus to 3.8.6

- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java
> Test Code Quarkus Site offers Java 21

- pom.xml
- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/QuarkusMavenPluginTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/SpecialCharsTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
Backports:
- https://github.com/quarkus-qe/quarkus-startstop/pull/403
- https://github.com/quarkus-qe/quarkus-startstop/pull/404
- https://github.com/quarkus-qe/quarkus-startstop/pull/405
- https://github.com/quarkus-qe/quarkus-startstop/pull/406
- https://github.com/quarkus-qe/quarkus-startstop/pull/407
> [3.15] Backport Quarkus-Startstop pre-3.15 clean-up PR

- pom.xml
Bump Quarkus to 3.15.2, lets see the CI
> [3.15] Bump Quarkus to 3.15.2

- pom.xml
Update quarkus.version and quarkus.ide to 3.15.3
> Update to 3.15.3

- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
Whitelist quarkus.version warning
> Whitelist quarkus.version warning

- README.md
- testsuite/src/it/java/io/quarkus/ts/startstop/StartStopTest.java
Introduce start-stop.skip.log-check property
> Introduce start-stop.skip.log-check property

- pom.xml
> [3.20] Update Quarkus to 3.20.0

- pom.xml
- testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
*  Bump Quarkus to 3.22.2 
* Adjust message pattern for gRPC
* https://github.com/quarkusio/quarkus/pull/47651
>  Bump Quarkus to 3.22.2 

- pom.xml
> Bump Quarkus to 3.15.5

- pom.xml
> [3.15] Bump Quarkus to 3.15.7

- pom.xml
> [3.20] Bump Quarkus to 3.20.3

- README.md
- pom.xml
- testsuite/pom.xml
- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusIbmSiteTest.java
- testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusRedHatSiteTest.java
Backport of https://github.com/quarkus-qe/quarkus-startstop/pull/602
> [3.27] Add profile and tests for IBM code.quarkus
