quarkus-qe/quarkus-startstop

README.md
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Logs.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

@rsvoboda  Added checking for Warnings and whitelisted 1.3.1.Final warnings we have now... e.g. 
```
2020-04-02 15:35:00,336 WARN  [io.qua.ver.run.VertxProducer] (Quarkus Shutdown Thread)
`io.vertx.reactivex.core.Vertx` is deprecated  and will be removed in a future version - 
it is recommended to switch to `io.vertx.mutiny.core.eventbus.Vertx`
```

Enforced checking for Warnings in logs

---

pom.xml
testsuite/pom.xml

Allows to execute just one thing at a time without enumerating exclusions, e.g. ``` -DincludeTags=codequarkus```

Partition included tests better

---

pom.xml
testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorBOMTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/StartStopTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/FakeOIDCServer.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Logs.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/WebpageTester.java
testsuite/src/main/resources/log4j2.xml

jboss-logging with log4j2, colorized console log
Fixes https://github.com/quarkus-qe/quarkus-startstop/issues/3
Example:

jboss-logging with log4j2, colorized console log

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

Whitelist error_prone_annotations artifact
this artifacts causes false positive failure on `Pattern.compile("(?i:.*(ERROR|WARN).*)");` check
```
[ERROR]   CodeQuarkusTest.notsupportedExtensionsSubset:143->testRuntime:109 MVNW_DEV log should not contain error or warning lines that are not whitelisted. See testsuite/target/archived-logs/io.quarkus.ts.startstop.CodeQuarkusTest/notsupportedExtensionsSubset/dev-run.log and check these offending lines:
Progress (5): guava-27.0.1-jre.jar (1.8/2.7 MB) | jackson-databind-2.10.2.jar (1.1/1.4 MB) | netty-codec-http2-4.1.45.Final.jar (459 kB) | wildfly-elytron-password-impl-1.11.2.Final.jar (98 kB) | error_prone_annotations-2.2.0.jar (12/14 kB)
```

Whitelist error_prone_annotations artifact

---

testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorBOMTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/MvnCmds.java

- Specify concrete Quarkus version for generated application and use proper local repo
- Quarkus bom is available for both community and product
Reasoning:
mvn io.quarkus:quarkus-maven-plugin:1.3.3.Final-redhat-00003:create ... doesn't create project with 1.3.3.Final-redhat-00003 version of Quarkus
but the latest community version of quarkus ...
so atm it's 1.5.0 which reports that reflection stuff in dev mode
1.4.2 was reporting it just in regular build
I have to update tests, we can specify -DplatformVersion=1.3.3.Final-redhat-00003 to use prod version and not the latest community one

Acceptance jobs fixes

---

testsuite/src/it/java/io/quarkus/ts/startstop/StartStopTest.java

Propagate Quarkus version in StartStopTest.
Currently it always defaults to 1.3.1.Final

Propagate Quarkus version in StartStopTest

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

Ignore Jandex warning for generator test.
Fixes https://github.com/quarkus-qe/quarkus-startstop/issues/19
Dev mode now exposes Jandex warning which was visible just during build.
This change happens starting with Quarkus 1.5.0.Final.

Ignore Jandex warning for generator test

---

app-full-microprofile/pom.xml
app-jax-rs-minimal/pom.xml
pom.xml

Drop provided org.eclipse.microprofile dependency
This is not relevant way for Quarkus and it pulls in weird dependencies like `javax.inject:javax.inject:jar:1.0.0.redhat-6` in case of prod bits

Drop provided org.eclipse.microprofile dependency

---

app-full-microprofile/src/main/java/com/example/quarkus/metric/MetricController.java

Metrics are not collected for private methods starting with Quarkus 1.5
Users get following warning:
`[WARNING] [io.quarkus.smallrye.metrics.deployment.SmallRyeMetricsProcessor] Private method is annotated with a metric: long getCustomerCount() in class com.example.quarkus.metric.MetricController. Metrics are not collected for private methods. To enable metrics for this method, make it at least package-private.`

Metrics are not collected for private methods starting with Quarkus 1.5

---

app-full-microprofile/pom.xml
app-jax-rs-minimal/pom.xml
testsuite/src/it/java/io/quarkus/ts/startstop/utils/MvnCmds.java

Update of app-jax-rs-minimal and app-full-microprofile applications
Using more Quarkus-like pom.xml structure
Using `<quarkus.package.type>native</quarkus.package.type>` approach in app-jax-rs-minimal and the old one in app-full-microprofile application
Solves [ěščřžýáíéůú and Îñţérñåţîöñåļîžåţîờñ](https://github.com/quarkus-qe/quarkus-startstop/pull/16/#issuecomment-653503598) issue in native mode
Checked locally with `mvn clean verify -Ptestsuite-community -Dquarkus.version=1.6.0.Final` command
@Rutzzzz fyi

Update of app-jax-rs-minimal and app-full-microprofile applications

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

Quarkus 1.6 properly registers classes for reflection, whitelist is not needed
Details in https://github.com/quarkusio/quarkus/issues/9954
Whitelist was needed for Quarkus 1.5

Quarkus 1.6 properly registers classes for reflection, whitelist is not needed

---

README.md
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/MvnCmds.java

Append properties starting with `quarkus.native` to the native image build command
For details see addition to README.md in this PR

Append properties starting with quarkus.native to the native image build command

---

app-full-microprofile/pom.xml
pom.xml

Move to Quarkus 1.7 - first step
Replacement for https://github.com/quarkus-qe/quarkus-startstop/pull/29
There are test failures that need to be resolved, probably issues on Quarkus side.

Move to Quarkus 1.7 - first step

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/Logs.java

Enhance checkLog() method to check not only against Erorrs and Warnings, but also against undesirable patterns that lower user experience with Quarkus.
Cover for [jira-quarkus-101](https://issues.redhat.com/browse/QUARKUS-101?jql=project%20%3D%20QUARKUS%20AND%20labels%20%3D%20no-qe-coverage%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC)

Enhance checkLog() method to check against black listed line patterns

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java

Removing repositories and pluginRepositories from pom.xml to ensure https://maven.repository.redhat.com/ga/ is not used when running against maven repo zip

Removing repositories and pluginRepositories from pom.xml

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Logs.java

Back-port to 1.7:
- Enhance checkLog() method to check against black listed line patterns
- Removing repositories and pluginRepositories from pom.xml

Back-port to 1.7: Enhance checkLog(), repositories and pluginRepositories removal

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/Logs.java

Fix SLF4J check to avoid picking things like `org.jboss.slf4j.JBossLoggerAdapter`

Fix SLF4J check

---

app-full-microprofile/src/main/resources/application.properties
app-generated-skeleton/application.properties
app-jax-rs-minimal/src/main/resources/application.properties

Use quarkus.log.console.color=false to prevent escape characters in log messages for Windows
Example: ![Screenshot 2021-01-27 14 15 54](https://user-images.githubusercontent.com/925259/106005327-6a602e00-60b4-11eb-8b9c-c99f9f1e6679.png)
This probably happens just if the Windows instance has enabled color support for `cmd`
https://github.com/quarkusio/quarkus/issues/1029#issuecomment-532383501

Use quarkus.log.console.color=false to prevent escape characters in log messages for Windows

---

.github/workflows/ci.yaml

Remove build-code-start from 1.11 branch, code.quarkus is always on the latest Quarkus version

Remove build-code-start from 1.11 branch, code.quarkus is always on the latest Quarkus version

---

pom.xml
testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java

- Quarkus 1.11.5.Final
- CodeQuarkusExtensions - update of supported extensions
- CodeQuarkusTest - Native tag for supportedExtensionWithCodeStarterWorksInNative tests
- CodeQuarkusSiteTest - use defined URL instead of hardcoded one

Quarkus ++  CodeQuarkusExtensions ++ CodeQuarkusTest ++ CodeQuarkusSiteTest update

---

app-full-microprofile/threshold.properties

Increase the threshold from 50 ms to 60 ms for the first OK request
GitHub CI sometimes reports numbers slightly above 50 ms limit
We are working on solution which could help us to follow the trends.

Increase the threshold from 50 ms to 60 ms for the first OK request

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

- `undertow-websockets` extension renamed to `websockets`. https://github.com/quarkusio/quarkus/pull/15068
- New whitelist entry for datasource. https://github.com/quarkusio/quarkus/pull/14960

Quarkus 1.13

---

pom.xml
testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java

Enhance testcase according to https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-821.md
Library HtmlUnit was used because the previous loading page solution doesn't wait for JavaScript to finish to fully load the page.
Logs were off, because HtmlUnit library is very strict to any mistake in CSS or javascript, which is okay for the browser, but not for HtmlUnit. Therefore a lot of logs were printed.

Enhance test for code.quarkus.redhat.com site

---

pom.xml
testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java

- Rename undertow-websockets to websockets
- The "smallrye-reactive-streams-operators" is not compatible with other reactive implementations: https://github.com/quarkusio/quarkus/issues/9754

Upgrade to 1.13.2.Final

---

testsuite/pom.xml
testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

- Add the following warning msg `org.apache.maven.settings.io.SettingsParseException: Unrecognised tag: 'blocked'` to the list of messages to be ignored as errors.

Maven 3.8.1 rise a warning msg that makes some test fail

---

testsuite/src/it/java/io/quarkus/ts/startstop/SpecialCharsTest.java

This is needed for slow Windows instances where 5 sec is not enough

[1.11] Increase timeout for SpecialCharacters test cases

---

README.md
app-generated-skeleton/AddedController.java
app-generated-skeleton/README.md
testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/URLContent.java

In reload test, in addition to modifying an existing class,
add a new class and verify that it has been loaded.
Covers https://issues.redhat.com/browse/QUARKUS-1020.

Extend Quarkus live reload test

---

README.md
app-generated-skeleton/AddedController.java
app-generated-skeleton/README.md
testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/URLContent.java

Backport of https://github.com/quarkus-qe/quarkus-startstop/pull/85.
Depends on https://github.com/quarkus-qe/quarkus-startstop/pull/86.
---
In reload test, in addition to modifying an existing class,
add a new class and verify that it has been loaded.
Covers https://issues.redhat.com/browse/QUARKUS-1020.

[1.11] Extend Quarkus live reload test

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

Whitelist warnings that are raised by maven wrapper 3.6.3 that doesn't recognize <mirror><blocked> tag

[1.11] Whitelist maven warnings raised by <mirror><blocked> tag

---

testsuite/src/it/resources/JSONtoEnum.java

shortId is before name in generated JSON now
example: `java JSONtoEnum https://code.quarkus.io/api/extensions` or `java JSONtoEnum https://code.quarkus.redhat.com/api/extensions`

shortId is before name in generated JSON now

---

.github/workflows/ci.yaml
pom.xml

Fix JVM build, dedicated job for format validation
Before this fix the JVM run was not doing a lot, just checking the root pom.xml

Fix JVM build, dedicated job for format validation

---

testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorBOMTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Logs.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/TestFlags.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

Move to new Quarkus platform without universe BOM
Also dropping usage of FakeOIDCServer as the OIDC extension doesn't need running Keycloak/RHSSO server when not used.

Move to new Quarkus platform without universe BOM

---

app-generated-skeleton/threshold.properties

Slight increase of timeout for Windows
To help with fails like https://github.com/quarkus-qe/quarkus-startstop/runs/3225713623?check_suite_focus=true
follow up action in https://trello.com/c/e3MxfB6b/913-check-performance-111-vs-21

Slight increase of timeout for Windows

---

pom.xml
testsuite/pom.xml
testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorBOMTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/NativeDebugTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/SpecialCharsTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/StartStopTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Apps.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/FakeOIDCServer.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/LogBuilder.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Logs.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/MvnCmds.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/TestFlags.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/URLContent.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/WebpageTester.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistProductBomJars.java
testsuite/src/it/resources/JSONtoEnum.java

Drop `@author` flag as git / https://github.com/quarkus-qe/quarkus-startstop/graphs/contributors give better overview
Drop Copyright from the files, root of the repo contains LICENSE file

JavaDoc and license related updates

---

app-generated-skeleton/application.properties
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

- DevService in dev mode is enabled by default, so could increase the started time and reload time adding noise to the final metrics

Disable devServices on dev mode

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java

Verified.
Test is failing because code.quarkus is not delivered, but productize version is taken from right path now

Change path for quarkus platform bom in CodeQuarkusSiteTest

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java

Verified.
Test is failing because code.quarkus is not delivered, but productize version is taken from right path now
Main PR https://github.com/quarkus-qe/quarkus-startstop/pull/107

[2.2] Change path for quarkus platform bom in CodeQuarkusSiteTest

---

pom.xml
testsuite/src/it/java/io/quarkus/ts/startstop/utils/MvnCmds.java

- Upgrade Quarkus to 2.2.2.Final.
Windows was failing using 2.1.1.Final due to https://github.com/quarkusio/quarkus/issues/19491, this issue was fixed in 2.1.4.Final, however I upgraded to the latest 2.2.2.Final as RHBQ will be based on it. cc @rsvoboda 
- Maintain Quarkus Ide Config independently:
As this dependency is not part of RHBQ, we need to use the upstream version always.
Dependabot will maintain it.

Bump Quarkus to 2.2.2.Final && Maintain Quarkus Ide Config independently

---

pom.xml
testsuite/src/it/java/io/quarkus/ts/startstop/utils/MvnCmds.java

Backport of https://github.com/quarkus-qe/quarkus-startstop/pull/108

[2.2] Bump Quarkus to 2.2.2.Final && Maintain Quarkus Ide Config independently

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java

This change is kind of expected as CodeQuarkus frontend has been refactored and the new platform focuses on streams ID (2.2) instead of the dependency version.
However, the dependency version is still present in the div title.
Link to the failing job: https://main-jenkins-csb-quarkusqe.apps.ocp4.prod.psi.redhat.com/view/UMB/job/rhbq-2.2-rhel8-jdk11-startstop-ts-acceptance-code-quarkus/11/

Update test case to verify the right version in CodeQuarkus

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java

This change is kind of expected as CodeQuarkus frontend has been refactored and the new platform focuses on streams ID (2.2) instead of the dependency version.
However, the dependency version is still present in the div title.
Backport of https://github.com/quarkus-qe/quarkus-startstop/pull/111

[2.2] Update test case to verify the right version in CodeQuarkus

---

testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Logs.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/MvnCmds.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/TestFlags.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

Quarkus Maven Plugin should be com.redhat.quarkus.platform for RHBQ and io.quarkus.platform for Upstream. I'm not very proud of how I did it, but didn't see any easier way.
++ Disable Quarkus Registry Client to boost generator Maven commands

Fix quarkus maven plugin group ID ++ Disable Quarkus Registry Client to boost generator Maven commands

---

pom.xml
testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorBOMTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/TestFlags.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/URLContent.java

RESTEasy reactive based extensions sets.
Generator related tests for now.
Side note: With 2.2.3.ER1 I've seen few non productized RESTEasy reactive artifacts
```
lib/main/io.quarkus.resteasy.reactive.resteasy-reactive-client-2.2.3.Final.jar
lib/main/io.quarkus.resteasy.reactive.resteasy-reactive-vertx-2.2.3.Final.jar
lib/main/io.quarkus.resteasy.reactive.resteasy-reactive-common-2.2.3.Final.jar
```
Is it know / tracked in JIRA?

RESTEasy reactive based extensions sets

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java

Re-enable extensions from platform participants
Back-port of https://github.com/quarkus-qe/quarkus-startstop/pull/121

[2.2] Re-enable extensions from platform participants

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

Example of failure in: https://github.com/quarkus-qe/quarkus-startstop/runs/3642297852?check_suite_focus=true
Caused by these traces:
```
TRACE [io.qua.builder] (build-49) Starting step "io.quarkus.jaxb.deployment.JaxbProcessor#ignoreWarnings"
```

Ignore some trace messages in Windows

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java

Verified with upstream code.quarkus.redhat.com. The main change is assertTrue(). PlatformVersion is skipped in upstream check

Adjust platform version XPath location

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

```
WARN  [io.qua.run.con.ConfigRecorder] (Quarkus Main Thread) Build time property cannot be changed at runtime:
- quarkus.smallrye-graphql.print-data-fetcher-exception was 'null' at build time and is now 'true'
```

Whitelist smallrye-graphql warning

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java

Support Quarkus main in generator tests
There is known issue for Quarkus main - https://github.com/quarkusio/quarkus/issues/21033
But I hesitate to do any workarounds for it in the tests. That bug needs to be fixed and it's not affecting our CI as we use just the released versions.

Support Quarkus main in generator tests

---

app-jax-rs-minimal/threshold.properties

Increase time.to.first.ok.request.threshold.ms for JAX-RS minimal app
Issue reported in https://github.com/quarkusio/quarkus/issues/21149
Should help to get green results with CI for now, let's see if the time can get lowered with some updates in Quarkus.

Increase time.to.first.ok.request.threshold.ms for JAX-RS minimal app

---

pom.xml
testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java

Playwright provides better API and has better JS support than htmlunit
Documentation is also better https://playwright.dev/java/docs/selectors/#quick-guide
Trello card with description of effort: https://trello.com/c/gqAsh7s6/1083-update-startstopts-tests-for-codequarkus-site-there-was-set-of-updates-to-enable-quarkiverse-extensions

Replace htmlunit with playwright

---

.github/workflows/ci.yaml
testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java

Use code.quarkus.redhat.com as default for 2.2 branch
Upstream code.quarkus is rolling target covered by main branch

[2.2] Use code.quarkus.redhat.com as default for 2.2 branch

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

Changes for Quarkus 2.6 - code.quarkus only
The rest is blocked because of https://github.com/quarkusio/quarkus/issues/22498
- Extensions moved to Quarkiverse in Quarkus 2.6 
- CodeQuarkusTest adjustments for Quarkus 2.6
- As dev services / docker are disabled for StartStopTS some workarounds need to be in place
- (execution with dev services is covered in quarkus-extensions-combinations)
- decreased number of unsupported extensions as several moved to Quarkiverse

Changes for Quarkus 2.6 - code.quarkus only

---

app-generated-skeleton/threshold.properties
pom.xml
testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorBOMTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

Move to Quarkus 2.6.2.Final
Kafka and Persistence codestarts are the biggest challenge.
Kafka code example has impact on dev mode reload time and introduces new log entries that need to be whitelisted.

Move to Quarkus 2.6.2.Final

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java

Drop platformArtifactId definition, workaround not needed

Drop platformArtifactId definition, workaround not needed

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java

Use core BOM instead of platform one for now

Use core BOM instead of platform one for now

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/MvnCmds.java

Failure related to reported issue:
https://issues.redhat.com/browse/QUARKUS-1417
Workaround applied to mvn command used in CodeQuarkusTest for native
build.

[2.2] Add workaround for FIPS failure in codequarkus

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java

code.quarkus - option to select stream
https://issues.redhat.com/browse/QUARKUS-1153
Test fails because https://code.quarkus.redhat.com doesn't have 2 streams yet, will have 2.2 and 2.7 for 2 months overlap once we release RHBQ 2.7 
PASS: `mvn test -Ptestsuite -Dtest=CodeQuarkusSiteTest#validatePresenceOfStreamVersionSelect -Dcode.quarkus.url=https://code.quarkus.io`
FAIL: `mvn test -Ptestsuite -Dtest=CodeQuarkusSiteTest#validatePresenceOfStreamVersionSelect`

code.quarkus - option to select stream

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java

Quarkus 2.7.5 / code.quarkus API related updates
- Stop using shortId approach which was removed from the API
- quarkus-oidc-token-propagation-reactive extension added in Quarkus 2.7.1.Final 
- Update of tested extensions with codestart, added RESTEasy extension where needed

Quarkus 2.7.5 / code.quarkus API related updates

---

app-full-microprofile/threshold.properties
app-jax-rs-minimal/threshold.properties

Increase windows.jvm.RSS.threshold.kB to mitigate GH Actions instabilities
Results are right under the threshold, sometimes going above by few kB.
Current limit was quite low, even the updated one is still quite low. But let's do the threshold updates step by step.

Increase windows.jvm.RSS.threshold.kB to mitigate GH Actions instabilities

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java

Make sure at least 2 streams are defined on code.quarkus
RHBQ 2.7 was released, https://code.quarkus.redhat.com/ has 2 versions defined.
Thomas said he doesn't want to remove 2.2 version definition.

Make sure at least 2 streams are defined on code.quarkus

---

pom.xml
testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/URLContent.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

Bump Quarkus from 2.7.5.Final to 2.9.2.Final
- codestarts for RESTEasy and RESTEasy Reactive synced  to have the same endpoint and same file name
- changes in spring-web codestart
- one issue found

Bump Quarkus from 2.7.5.Final to 2.9.2.Final

---

.github/workflows/ci.yaml
README.md

Updates GraalVM/Mandrel version to 22.2.

Update native image builders - use version 22.2

---

.github/workflows/ci.yaml
testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorBOMTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java

+ Use method name based directory for generator tests
+ Minor update to use a bit longer root GH Action name, code.quarkus name update 
Method name based directory for generator tests prevents the issue we see from time to time on Windows machines with slow IO - like in this run https://github.com/quarkus-qe/quarkus-startstop/actions/runs/3078997244

Use method name based directory for generator tests

---

pom.xml
testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java

Move to Quarkus 2.13.0.Final, force Java 11 for code.quarkus apps

Move to Quarkus 2.13.0.Final, force Java 11 for code.quarkus apps

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java

Force Java 11 for code.quarkus apps
Context of the change: https://issues.redhat.com/browse/QUARKUS-2451

[2.7] Force Java 11 for code.quarkus apps

---

.github/workflows/ci.yaml
pom.xml

Bump Quarkus to 2.13.2.Final
Java 17 based GraalVM is the default starting Quarkus 2.13

Bump Quarkus to 2.13.2.Final

---

app-jax-rs-minimal/threshold.properties

Bump first.ok.request.threshold.ms to 40ms for app-jax-rs-minimal
Investigation for the increase is tracked in https://issues.redhat.com/browse/QUARKUS-2456

Bump first.ok.request.threshold.ms to 40ms for app-jax-rs-minimal

---

testsuite/src/it/java/io/quarkus/ts/startstop/StartStopTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java

- Allow runing in intellij
- Provide `-DdisableCleaup` option to disable cleanup of artefacts, allows easier debugging
- Validate build logs before trying to capture native image stats.

Minor fixes

---

.github/workflows/ci.yaml
testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java

Remove repositories definition for code.quarkus tests
Needed for RH based instance, but it's better to have it already in main (less work when backporting)

Remove repositories definition for code.quarkus tests

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java

Download apps from 2.13 stream
CodeQuarkus tests are Quarkus version agnostic, they run against the instance and check if the app can be built / used, thus we should define stream in code. We can't rely on parsing from Quarkus version.

[2.13] Download apps from 2.13 stream

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java

Fix repos removal for code.quarkus
Line 101 is the right place for the method call, the one on line 103 needs to be dropped
PR https://github.com/quarkus-qe/quarkus-startstop/pull/247 introduce a side effect which would be noticed only when we branch and run against product maven repo zip

Fix repos removal for code.quarkus

---

.github/workflows/ci.yaml

Update GH actions to use latest versions
This removes warnings from GH Actions runs
Backport of https://github.com/quarkus-qe/quarkus-startstop/pull/251 into 2.13 branch

[2.13] Update GH actions to use latest versions

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commons.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

Fixes failures due to two upstreams issues:
Missing classes: https://github.com/quarkusio/quarkus/issues/30508
Missing builder image: https://github.com/quarkusio/quarkus/issues/30738

[2.13] Allow two warnings

---

testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java

`QPID ` is going to be part of RHBQ 2.13.7. This PR add this extension to `ArtifactGeneratorTest`

[2.13] Add QPID to ArtifactGeneratorTest on RHBQ 2.13

---

README.md

Update documentation regarding new builder images introduced in Quarkus 2.14
PR with the change - https://github.com/quarkusio/quarkus/pull/27997
NEW is active - https://quay.io/quarkus/ubi-quarkus-mandrel-builder-image
OLD is without update for 3 months - https://quay.io/quarkus/ubi-quarkus-native-image

Update README with newer builder image introduced in Quarkus 14

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java

On 2.13 codeQuarkus is loading the latest stream (2.13), but on future releases we need to force this version to the expected one.
This PR force branch 2.13 to point to the expected codeQuarkus version

[2.13] Ensure codequarkus is pointing to 2.13 in future releases

---

.github/workflows/ci.yaml
pom.xml
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java

QuarkusMavenPluginTest fails on the old verison, due to lack of descriptors in registry, so we need to update Quarkus version to the latest (2.16.3.Final ATM)
Also added debugging for commands being run

Switch to the latest Quarkus and do a little refactoring

---

app-full-microprofile/pom.xml
app-full-microprofile/threshold.properties
app-jax-rs-minimal/pom.xml
app-jax-rs-minimal/threshold.properties
testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

Move app-full-microprofile and app-jax-rs-minimal to RESTEasy Reactive
Includes change of thresholds based on experiments on my local machine (MBP 2019) and GH actions.
Fixes https://github.com/quarkus-qe/quarkus-startstop/issues/230

Move app-full-microprofile and app-jax-rs-minimal to RESTEasy Reactive

---

README.md
testsuite/src/it/java/io/quarkus/ts/startstop/StartStopTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java

Cold start option for StartStopTest
Fixes https://github.com/quarkus-qe/quarkus-startstop/issues/263
Difference in results is noticeable, cold start is slower than the one with warmup. Cold start is supposed to give more stable results.
Commands executed in PSI (no Linux baremetal machine available to me atm):
- `mvn test -Ptestsuite -Dtest=StartStopTest#fullMicroProfileJVM -Dstart-stop.cold-start -Dstart-stop.iterations=50`
- `mvn test -Ptestsuite -Dtest=StartStopTest#fullMicroProfileJVM -Dstart-stop.iterations=50`
Run 1:
```
[i.q.t.s.StartStopTest] (testRuntime) AVG timeToFirstOKRequest without min and max values: 1527
[i.q.t.s.StartStopTest] (testRuntime) AVG rssKb without min and max values: 196779
[i.q.t.s.StartStopTest] (testRuntime) AVG timeToFirstOKRequest without min and max …
```

Cold start option for StartStopTest

---

testsuite/src/it/java/io/quarkus/ts/startstop/QuarkusMavenPluginTest.java

Disable `updateTarget` test on Windows due to Quarkus bug https://github.com/quarkusio/quarkus/issues/33403

Disable updateTarget test on Windows due to Quarkus bug

---

pom.xml
testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

- Bump Quarkus to 3.1.0.Final
- Whitelist for quarkusio/quarkus/issues/33825"

Bump Quarkus to 3.1.0.Final

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java

Verifies https://issues.redhat.com/browse/QUARKUS-3194. I tested it with 2.13.8.CR2, but couldn't verify failing against 2.13.7 as it is not present in code.quarkus anymore (well, I think that was the reason..), but `io.quarkus.ts.startstop.utils.Logs#checkLog` would fail if there were warnings.

[2.13] Add MongoDB to CodeQuarkusTest native runs to verify no warnings logged

---

app-full-microprofile/threshold.properties
app-generated-skeleton/threshold.properties
app-jax-rs-minimal/threshold.properties

Bump thresholds to be more GH Actions env friendly, numbers are based on analysis of the last 10 failed GH actions runs.
GH Actions env doesn't provide perf guarantees and recently we had several failures due to slow runners. Execution on bare metal machine and PSI based machine didn't reveal any regression in Quarkus.
Bare metal (macOS with minimal set of apps running):
```
git checkout main
mvn clean verify -Ptestsuite -Dtest=StartStopTest#fullMicroProfileJVM -Dquarkus.version=3.0.1.Final -Dstart-stop.iterations=60 | grep AVG
mvn clean verify -Ptestsuite -Dtest=StartStopTest#fullMicroProfileJVM -Dquarkus.version=3.1.1.Final -Dstart-stop.iterations=60 | grep AVG
git checkout rootless
mvn clean verify -Ptestsuite -Dtest=StartStopTest#fullMicroProfileJVM -Dquarkus.version=2.13.8.Final …
```

Bump thresholds to be more GH Actions env friendly

---

app-jakarta-rest-minimal/threshold.properties

Increase native `time.to.first.ok.request` threshld for `app-jakarta-rest-minimal` to make GitHub actions pass.
10 recent GH daily runs failed on exceeding this threshold with an average time of 44.5 ms.
The test has been manually ran (100 iterations) on a local environment and on a RHOS-D RHEL8 machine with no conclusive indication of increased time.
Local results:
```
3.2.1.Final:  17, 16
3.2.2.Final:  17, 18
3.2.3.Final:  18, 17
3.2.4.Final:  16, 18
```
RHOS-D results:
```
3.2.1.Final:  22, 22
3.2.2.Final:  22, 22
3.2.3.Final:  22, 22
3.2.4.Final:  22, 22
```

Increase native threshold for GH actions

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/Logs.java

`SLF4J:` pattern, if case-insensitive, might accidentally match artifact coordinates (e.g. `org.slf4j:slf4j-api:pom:2.0.6`). This might falsely report a benign log line.
See e.g. a failure in
https://github.com/quarkus-qe/quarkus-startstop/actions/runs/5956999432/job/16158894853.

Fix SLF4J log error detection

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java

CodeQuarkusSiteTest - build-scoped instances have just the current stream defined
Relates to https://issues.redhat.com/browse/QUARKUS-3299

CodeQuarkusSiteTest - build-scoped instances have just the current stream defined

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java

[3.2]  CodeQuarkusSiteTest - build-scoped instances have just the current stream defined
Backport of #296 to 3.2 branch
Relates to https://issues.redhat.com/browse/QUARKUS-3299

[3.2]  CodeQuarkusSiteTest - build-scoped instances have just the current stream defined

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java

build-scoped instances have just the current stream defined

[2.13] code.quarkus - build-scoped instances have just the current stream defined

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

Whitelist xml-apis relocation warning

[3.2] Whitelist xml-apis relocation warning

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistProductBomJars.java

As the title say. Tested locally and these artifact not appearing in error output.

Allow jna and jna-platform artifacts to be not productized.

---

testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java

Add quarkus-elasticsearch-rest-client to generator tests, TP in 3.2
backport of https://github.com/quarkus-qe/quarkus-startstop/pull/308

[3.2] Add quarkus-elasticsearch-rest-client to generator tests, TP in 3.2

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

Whitelist Unknown module: org.graalvm.nativeimage issue https://github.com/quarkusio/quarkus/issues/36053.
Adding to Linux specific whitelists as we use Mandrel just on Linux.

Whitelist Unknown module: org.graalvm.nativeimage issue

---

app-full-microprofile/threshold.properties
app-jakarta-rest-minimal/threshold.properties
pom.xml
testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

- Bump Quarkus to 3.4.1, oidc client filter depends on RESTEasy Classic 
- Increase of the thresholds (mainly motivated by https://issues.redhat.com/browse/QUARKUS-3426)

Bump Quarkus to 3.4.1, oidc client filter depends on RESTEasy Classic 

---

app-full-microprofile/threshold.properties
app-jakarta-rest-minimal/threshold.properties
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

- Increase of the thresholds to sync with main, mainly for QUARKUS-3426
- https://github.com/quarkusio/quarkus/blob/3.2.6.Final/core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java#L23 uses the same image as main
- warning whitelist for org.slf4j artifacts (env issue on GH Actions)
- Use code.quarkus.redhat.com for CodeQuarkusTest

[3.2] Increase of the thresholds, warning whitelist

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

Whitelist BlockedThreadChecker warning for Windows
GH Actions Windows runners are sometimes slow

Whitelist BlockedThreadChecker warning for Windows

---

testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java

Test manyReactiveExtensionsSetA fails on github CI on timeout.
see https://github.com/quarkus-qe/quarkus-startstop/actions/runs/6398976351/job/17370208108#step:4:993
Tested .jar app is killed (timed out) in the midle of booting.

Extend timeout on ArtifactGeneratorTest

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java

Comment out Hazelcast, external participants are not often part of the testing instances

[2.13] Comment out Hazelcast, external participants are not often part of the testing instances

---

pom.xml

Define test scope for dependencies used in testsuite module
With Quarkus 3.4 these deps get pulled into final application classpath for app-* modules, e.g. `log4j-core`.
There were some changes ion Quarkus reflecting more stuff from the parent pom file.

Define test scope for dependencies used in testsuite module

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/MvnCmds.java

Set -Xmx96m for native app runs to have upper limit when measuring RSS

Set -Xmx96m for native app runs to have upper limit when measuring RSS

---

.github/workflows/ci.yaml

Change CI definition from latest mandrel version to specific version (23.0.1.2-Final) as the newest one was built only by JDK 21. This is specific for windows native.

Change mandrel version in CI

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

This fixes daily, but property was deprecated long ago, is still injected by Quarkus it self so looking what the cause and why it't happening only with 3.5. Link to Quarkus commit [https://github.com/quarkusio/quarkus/commit/c4d6bdcea1d14c4fd2a66e3ea48778e832ca0fe7](https://github.com/quarkusio/quarkus/commit/c4d6bdcea1d14c4fd2a66e3ea48778e832ca0fe7)

Add allowed warn in log containing quarkus.mongodb.native.dns.

---

pom.xml
testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

Bump Quarkus to 3.5.0
Allow-list native warnings about experimental VM options
- `-H:ReflectionConfigurationResources`
- Reported in `netty`: https://github.com/netty/netty/issues/13595.
- Fixed in `netty`: https://github.com/netty/netty/pull/13596.
- See also similar issue in https://github.com/Karm/mandrel-integration-tests/issues/190 and its workaround in https://github.com/Karm/mandrel-integration-tests/pull/203.
- `-H:Log=registerResource, -H:Log=registerResource:`
- Added explicitly by `APP_FULL_MICROPROFILE` config.
- Typical use case documented in Quarkus Native Reference Guide, the documentation was added in https://github.com/quarkusio/quarkus/pull/36494.
- Allow-listed, instead of using `-H:+UnlockExperimentalVMOptions` / `-H:-UnlockExperimentalVMOptions`, to avoid errors with …

Bump Quarkus to 3.5.0, native warnings, config-yaml warning

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java

Latest code.quarkus introduced config per stream and 2.13 has default on Java 11
Fix is specific for 2.13 branch. No need to update main or 3.2 branch.

[2.13] Latest code.quarkus introduced config per stream and 2.13 has default on Java 11

---

.github/workflows/ci.yaml
README.md
pom.xml
testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

Quarkus changed, we need to get Quarkus Startstop ready for 3.7. See also https://github.com/quarkus-qe/quarkus-test-suite/pull/1556.

Move Java baseline to 17

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java

Current version doesn't work as 3.2.6 and 3.2.9 and greater than 3.2.10. I could fix sorting, but it feels like rubbish way to determine Quarkus platform version anyway, hence using system property. It's RedHat code.quarkus tests, therefore we do not run it for upstream Quarkus version.
P.S. I'll create port PR for main if this gets accepted, but now 3.2 branch is more important as time is pressing.

[3.2] Use Quarkus platform version from system variable

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

Daily build fails over:
```
[ERROR] Failures: 
[ERROR]   CodeQuarkusTest.supportedExtensionsSubsetB:185->testRuntime:155 MVNW_DEV log should not contain error or warning lines that are not whitelisted. See testsuite/target/archived-logs/io.quarkus.ts.startstop.CodeQuarkusTest/supportedExtensionsSubsetB/dev-run.log and check these offending lines: 
2024-02-09 15:39:07,725 WARN  [io.qua.arc.dep.SplitPackageProcessor] (build-46) Detected a split package usage which is considered a bad practice and should be avoided. Following packages were detected in multiple archives:  ==> expected: <true> but was: <false>
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
```
which in logs you can see is SR RM, I've opened issue https://github.com/quarkusio/quarkus/issues/38711
``` …
```

Whitelist SmallRye Reactive Messaging split package usage warning logs

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

Whitelists deprecation warning for which daily build is also failing. The issue is fixed in Quarkus https://github.com/quarkusio/quarkus/pull/38710 but we need to wait for a next micro release.

Whitelist GraphQL deprecation warn till 3.7.3 released

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java

This extension is deprecated and now OpenTelemetry is using. Left after the https://github.com/quarkus-qe/quarkus-startstop/pull/332

Remove camel-quarkus-opentracing from extension list

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java

https://code.quarkus.redhat.com/ only offers Java 17. We need to wait till https://github.com/quarkusio/quarkus/issues/38732 is fixed in a released Quarkus version.

Disable Code Quarkus site Java 11 check till fixed upstream

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java

String '-redhat-' can detect old format (3.2.11.Final-redhat-00001) but fails on the new one (3.8.3.redhat-00002)

Fix detection of redhat version

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java

Since 3.8.3, code.quarkus may contain version number in HTML elements of different classes: `quarkus-stream`, `quarkus-stream redhat` and so on. To adapt to that, we need to change our search conditions. See https://issues.redhat.com/browse/QUARKUS-4187 for details

Change the search for platform version

---

README.md
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/MvnCmds.java

Maven inspects the `$JAVA_HOME` environment variable to determine which java binary to use to build a project. 
The `MvnCmds` enum commands are used to fork new processes for testing, by calling `java` in the forked process. This resolves the java binary from the environment `$PATH`.  If these differ, the tests can fail as a newer java version could be specified in `$JAVA_HOME` when the mvn process is started, and an older java version could be used the test application(s)
This PR resolves the jara binary that is being used to build the applications and uses the same java binary to start the applications in a forked process. 
This ensures that the JDK that was used to build the test application(s) is the same JDK used to run them
**Please note**: I have not been able to test this change …

Resolve java home dir from system properties

---

README.md
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/MvnCmds.java

Backport of https://github.com/quarkus-qe/quarkus-startstop/pull/364
---
Maven inspects the `$JAVA_HOME` environment variable to determine which java binary to use to build a project. 
The `MvnCmds` enum commands are used to fork new processes for testing, by calling `java` in the forked process. This resolves the java binary from the environment `$PATH`.  If these differ, the tests can fail as a newer java version could be specified in `$JAVA_HOME` when the mvn process is started, and an older java version could be used the test application(s)
This PR resolves the jara binary that is being used to build the applications and uses the same java binary to start the applications in a forked process. 
This ensures that the JDK that was used to build the test application(s) is the same JDK …

[3.8] Resolve java home dir from system properties

---

app-generated-skeleton/index.html
pom.xml
testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorBOMTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/QuarkusMavenPluginTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/URLContent.java

Updating Quarkus and Quarkus config version to 3.2.12.Final
Backport the code.quarkus.io not generating index.html
Also backport `Run plugin tests in separate directories` causing errors as it was update skeleton to 3.9 which have different rest artifact name

[3.2] Bump Quarkus to 3.2.12.Final and add some backports

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistProductBomJars.java

This reverts commit 8465e92d93ab8080415df84c2dce3df6f95f0dad.
See https://issues.redhat.com/browse/QUARKUS-4289 fro details

[3.8] Revert "Allow kotlin libraries not to be productised for 3.8"

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java

-  Use code.quarkus.redhat.com for CodeQuarkusTest 
-  Run validateQuarkusVersionMatch against 3.8 stream

[3.8] RHBQ 3.8 changes

---

app-full-microprofile/pom.xml
app-jakarta-rest-minimal/pom.xml
pom.xml
testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

Quarkus rename webjars-locator to web-deoendency-locator. See [migration guide](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.11). This will fix daily CI
Also bumping Quarkus as we miss 3.10 release 
`quarkus.package.type` was changed in Quarkus 3.10 see [migration guide](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.10)

Rename webjars locator and bump Quarkus version

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/URLContent.java

Check /data/hello REST endpoint as the first one
Motivation: timeToFirstOKRequest in https://github.com/quarkus-qe/quarkus-startstop/blob/main/testsuite/src/it/java/io/quarkus/ts/startstop/StartStopTest.java#L139 to be checked against REST endpoint and not against index.html as pointed out by @franz1981

Check /data/hello REST endpoint as the first one

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

Fix whitelist regex for issue causing our daily tests to fail. Failure is related to https://github.com/quarkusio/quarkus/issues/41351.
It seems to still be the same/similar issue, but original regex didn't work with line separator "\n" as regex charater "." (any character) does not match newline.

Fix whitelist regex for 41351 issue

---

README.md
testsuite/src/it/java/io/quarkus/ts/startstop/utils/LogBuilder.java

Smaller fixes in reporting and times recording
- Shutdown time can be 0.000s, especially in native mode 
- Fix typo in kB

Smaller fixes in reporting and times recording

---

app-full-microprofile/threshold.properties

Increase RSS memory limit for MP native binary (used in GH Actions runs)
Details about increased memory usage in https://github.com/quarkusio/quarkus/issues/42506

Increase RSS memory limit for MP native binary

---

app-full-microprofile/pom.xml
app-jakarta-rest-minimal/pom.xml
testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

Switch back to reactive artifacts for easier 3.8 and 3.15 comparison
One can do things like this without the need to change branches:
```
mvn clean package -f app-full-microprofile -Dnative -Dquarkus.native.monitoring=jfr -Dquarkus.version=3.13.2
mvn clean package -f app-full-microprofile -Dnative -Dquarkus.native.monitoring=jfr -Dquarkus.version=3.8.5
```
Artifacts like `quarkus-rest-jackson` were introduced in 3.9, there are relocations available for older artifacts names and thus the testing apps can be simply compiled with 3.8 and 3.latest

Switch back to reactive artifacts for easier 3.8 and 3.15 comparison

---

.github/workflows/ci.yaml

Reduces log heaviness. Adds --no-transfer-progress for maven execution to reduce "Downloading ...." messages

Reduce log size in CI runs by suppressing download transfer progress

---

.github/workflows/ci.yaml

Backports https://github.com/quarkus-qe/quarkus-startstop/pull/391

[3.8] Reduce log size in CI runs by suppressing download transfer progress

---

.github/workflows/ci.yaml

Backports https://github.com/quarkus-qe/quarkus-startstop/pull/391

[3.2] Reduce log size in CI runs by suppressing download transfer progress

---

app-full-microprofile/pom.xml
app-jakarta-rest-minimal/pom.xml
testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

Rename dependencies as was done in https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.9

Rename quarkus-rest(easy) dependencies

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java

Fix failures detected in https://github.com/quarkus-qe/quarkus-startstop/pull/393
https://code.quarkus.redhat.com/?S=com.redhat.quarkus.platform%3A3.2 page should be used in `validatePresenceOfJavaVersionSelect`  test to retrieve correct information about current supported Java versions

[3.2] Run Java versions validation against 3.2 stream

---

pom.xml
testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java

* Run relevant code.quarkus tests against 3.15 stream
* Move to Quarkus 3.15.0.CR1

[3.15] Use Quarkus 3.15.0.CR1, code.quarkus tests against 3.15 stream

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java

Fix CodeQuarkusSiteTest, do not modify fallback webPageUrl
Fixes failure from https://github.com/quarkus-qe/quarkus-startstop/pull/399 which was merged before I could get to it.

[3.15] Fix CodeQuarkusSiteTest, do not modify fallback webPageUrl

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

Whitelist for failed exports of spans after shutdown initiation
Targeting just 3.8 as 3.15 and main have slightly reworked some parts around shutdown. The "Failed to export spans. The request could not be executed. Full error message: null [Error Occurred After Shutdown]" message may or may not occur there.

[3.8] Whitelist for failed exports of spans after shutdown initiation

---

testsuite/src/it/java/io/quarkus/ts/startstop/QuarkusMavenPluginTest.java

https://github.com/quarkusio/quarkus/issues/33403 is closed and based on comments I expect this to be fixed. Linked issue mentions Windows 10, but I have no tools to test it there and I don't see a point to have this disabled if CI passes.

Enable QuarkusMavenPluginTest#updateTarget on Windows

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java
testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java

- Quarkus Hazelcast extension cannot be found in RHBQ/Community platform, looks dead
- https://issues.redhat.com/browse/QUARKUS-1294 is fixed, but Quarkus REDIS client is already among extensions, so dropping duplicate record
- dropping `quarkus-elasticsearch-rest-high-level-client` as it doesn't exist anymore https://github.com/quarkusio/quarkus/pull/31997
- adding back Quarkus CSFR as this PR https://github.com/quarkus-qe/quarkus-startstop/commit/25587f2cf474320be36b4a25faa80b5f626b3608 said it should be in RESTEasy Reactive. No idea what it means, but I checked and the CSRF is not included in Quarkus REST
- adding a bucket for RESTEasy Classic extensions as they cannot be mixed with Quarkus REST extensions, it's but a smoke check

Refactor CodeQuarkusExtensions enum by adding REST CSFR extension, RESTEasy Classic bucket and drop commented out code that is no longer relevant

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

Dropping whitelisted log messages as:
- https://github.com/quarkusio/quarkus/issues/34626 is fixed
- https://github.com/quarkusio/quarkus/issues/33825 is fixed
- https://github.com/quarkusio/quarkus/issues/36775 is fixed
- https://github.com/quarkusio/quarkus/issues/38711 is fixed
- https://github.com/quarkusio/quarkus/issues/37532 is fixed
- we cannot run this project with Quarkus versions older than 3.2 (use dedicated branches)

Remove whitelisted log messages for fixed issues

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java

Adjust code.quarkus site tests to the new layout with presets, this fixes failures we have in daily CI - https://github.com/quarkus-qe/quarkus-startstop/actions/workflows/ci.yaml
* https://code.quarkus.redhat.com was updated to have presets 
* new pageLoadedSelector was identified to work with old and new version
* `validatePresenceOfSupportedFlags` now checks grpc extension URL because the default page has presets without a visible list of extensions
Example commands for execution (code-3-15-1 has old version deployed):
```
mvn clean verify -Ptestsuite-community-no-native -Dtest=CodeQuarkusSiteTest
mvn clean verify -Ptestsuite-community-no-native -Dtest=CodeQuarkusSiteTest -Dcode.quarkus.url=https://code-3-15-1-redhat-00003.apps.ocp-c1.prod.psi.redhat.com/
```
I will create backports for …

Adjust code.quarkus site tests to the new layout with presets

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java

Backport of https://github.com/quarkus-qe/quarkus-startstop/pull/409
* new pageLoadedSelector was identified to work with old and new version
* validatePresenceOfSupportedFlags now checks grpc extension URL because the default page has presets without a visible list of extensions

[3.15] Adjust code.quarkus site tests to the new layout with presets

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java

Backport of https://github.com/quarkus-qe/quarkus-startstop/pull/409
* new pageLoadedSelector was identified to work with old and new version
* validatePresenceOfSupportedFlags now checks grpc extension URL because the default page has presets without a visible list of extensions

[3.8] Adjust code.quarkus site tests to the new layout with presets

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java

* Chromium managed by Playwright doesn't properly work on aarch64 right now, so let's use Firefox in CodeQuarkusSiteTest.

Switch site test to use Firefox

---

testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java

* Chromium managed by Playwright doesn't properly work on aarch64 right now, so let's use Firefox in CodeQuarkusSiteTest.
(cherry picked from commit 1e2fab86c71a10d009b62b33c2045bb6c962f850)
Backport of https://github.com/quarkus-qe/quarkus-startstop/pull/412

[3.15] Switch site test to use Firefox

---

pom.xml

Bumping Quarkus to 3.16.2, as this is bigger bump let's see what CI is thinking about it. If there are failiures I'll look at them in some free time this week.

Bump Quarkus to 3.16.2

---

pom.xml
testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java

Doned because RHBQ 3.15.1 was released

[3.15] Use code.quarkus.redhat.com and the latest version of Quarkus

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

Removing the allowed log lines which should be fixed.

Remove allowed log lines

---

pom.xml

Switch quarkus.platform.group-id to io.quarkus.platform
Should help with premature updates like https://github.com/quarkus-qe/quarkus-startstop/pull/460. We need platform releases.

Switch quarkus.platform.group-id to io.quarkus.platform

---

testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistProductBomJars.java

Whitelisting LatencyUtils due to https://issues.redhat.com/browse/QUARKUS-5937 so that we can get jobs green.

[3.20] Whitelist LatencyUtils for 3.20.0

---

pom.xml
testsuite/src/it/java/io/quarkus/ts/startstop/ArtifactGeneratorTest.java

* Bump quarkus.version from 3.21.4 to 3.22.1
* REST Data Panache modules no longer work with quarkus-resteasy modules

Bump quarkus.version from 3.21.4 to 3.22.1

---

pom.xml
testsuite/src/it/java/io/quarkus/ts/startstop/utils/WhitelistLogLines.java

Version upgrade in POM file :
```
<quarkus.version>3.20.1</quarkus.version>
<quarkus-ide-config.version>3.20.1</quarkus-ide-config.version>
```

bump-to-3.20.1

---

pom.xml

Bump versions to 3.20.2
`
<quarkus.version>3.20.2</quarkus.version>
<quarkus-ide-config.version>3.20.2</quarkus-ide-config.version>
`

Bump versions to 3.20.2
